services:
  backend:
    build: ./backend
    ports:
      - "8777:8777"
    volumes:
      - ./backend/:/app/
    env_file:
      - .env/.env.backend

  # front:
  #   build: ./frontend
  #   ports:
  #     - "8778:8778"
  #   volumes:
  #     - ./frontend/:/app-frontend/
  #   env_file:
  #     - .env/.env.frontend
