version: '0.1'

services:
  web:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./src/:/app/src/
    env_file:
      - .env
    depends_on:
      - db

  pgweb:
    restart: always
    image: sosedoff/pgweb
    ports:
      - "${PGWEB_PORT}:${PGWEB_PORT}"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"

volumes:
    postgres_data:
